// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// adaptive_metropolis_cpp
Rcpp::List adaptive_metropolis_cpp(Rcpp::Function target_density, const arma::vec& initial_state, const int n_iter, const arma::mat& initial_proposal_covariance, const int adapt_start, const double epsilon);
RcppExport SEXP _AdaptiveMCMCWorkflow_adaptive_metropolis_cpp(SEXP target_densitySEXP, SEXP initial_stateSEXP, SEXP n_iterSEXP, SEXP initial_proposal_covarianceSEXP, SEXP adapt_startSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type target_density(target_densitySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< const int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initial_proposal_covariance(initial_proposal_covarianceSEXP);
    Rcpp::traits::input_parameter< const int >::type adapt_start(adapt_startSEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_metropolis_cpp(target_density, initial_state, n_iter, initial_proposal_covariance, adapt_start, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// basic_metropolis_cpp
Rcpp::List basic_metropolis_cpp(Rcpp::Function target_density, const arma::vec& initial_state, const int n_iter, const arma::mat& proposal_covariance);
RcppExport SEXP _AdaptiveMCMCWorkflow_basic_metropolis_cpp(SEXP target_densitySEXP, SEXP initial_stateSEXP, SEXP n_iterSEXP, SEXP proposal_covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type target_density(target_densitySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< const int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type proposal_covariance(proposal_covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(basic_metropolis_cpp(target_density, initial_state, n_iter, proposal_covariance));
    return rcpp_result_gen;
END_RCPP
}
// dram_cpp
Rcpp::List dram_cpp(Rcpp::Function target_density, const arma::vec& initial_state, const int n_iter, const arma::mat& initial_proposal_covariance, const int adapt_start, const double delayed_rejection_scale, const double epsilon);
RcppExport SEXP _AdaptiveMCMCWorkflow_dram_cpp(SEXP target_densitySEXP, SEXP initial_stateSEXP, SEXP n_iterSEXP, SEXP initial_proposal_covarianceSEXP, SEXP adapt_startSEXP, SEXP delayed_rejection_scaleSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type target_density(target_densitySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< const int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initial_proposal_covariance(initial_proposal_covarianceSEXP);
    Rcpp::traits::input_parameter< const int >::type adapt_start(adapt_startSEXP);
    Rcpp::traits::input_parameter< const double >::type delayed_rejection_scale(delayed_rejection_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(dram_cpp(target_density, initial_state, n_iter, initial_proposal_covariance, adapt_start, delayed_rejection_scale, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// robust_adaptive_metropolis_cpp
Rcpp::List robust_adaptive_metropolis_cpp(Rcpp::Function target_density, const arma::vec& initial_state, const int n_iter, const arma::mat& initial_proposal_covariance, const double target_acceptance, const double adapt_exponent);
RcppExport SEXP _AdaptiveMCMCWorkflow_robust_adaptive_metropolis_cpp(SEXP target_densitySEXP, SEXP initial_stateSEXP, SEXP n_iterSEXP, SEXP initial_proposal_covarianceSEXP, SEXP target_acceptanceSEXP, SEXP adapt_exponentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type target_density(target_densitySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< const int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initial_proposal_covariance(initial_proposal_covarianceSEXP);
    Rcpp::traits::input_parameter< const double >::type target_acceptance(target_acceptanceSEXP);
    Rcpp::traits::input_parameter< const double >::type adapt_exponent(adapt_exponentSEXP);
    rcpp_result_gen = Rcpp::wrap(robust_adaptive_metropolis_cpp(target_density, initial_state, n_iter, initial_proposal_covariance, target_acceptance, adapt_exponent));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AdaptiveMCMCWorkflow_adaptive_metropolis_cpp", (DL_FUNC) &_AdaptiveMCMCWorkflow_adaptive_metropolis_cpp, 6},
    {"_AdaptiveMCMCWorkflow_basic_metropolis_cpp", (DL_FUNC) &_AdaptiveMCMCWorkflow_basic_metropolis_cpp, 4},
    {"_AdaptiveMCMCWorkflow_dram_cpp", (DL_FUNC) &_AdaptiveMCMCWorkflow_dram_cpp, 7},
    {"_AdaptiveMCMCWorkflow_robust_adaptive_metropolis_cpp", (DL_FUNC) &_AdaptiveMCMCWorkflow_robust_adaptive_metropolis_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_AdaptiveMCMCWorkflow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
