#' AdaptiveMCMCWorkflow: Teaching Adaptive MCMC Slowly and Explicitly
#'
#' `AdaptiveMCMCWorkflow` is a teaching package for adaptive random-walk MCMC.
#' The computational kernels live in C++ via `RcppArmadillo`, while the target
#' distributions, summaries, plots, and diagnostics live in R.
#'
#' The package focuses on four algorithms:
#'
#' - basic Metropolis
#' - Adaptive Metropolis (AM)
#' - Robust Adaptive Metropolis (RAM)
#' - Delayed Rejection Adaptive Metropolis (DRAM)
#'
#' The package is built around a small set of sampler wrappers, target
#' constructors, summary helpers, and plotting helpers. In this source repo,
#' the simplest end-to-end demonstration is the script `run_adaptive_mcmc_demo.R`.
#'
#' The package does not claim to prove general adaptive MCMC validity from
#' simulation. Instead, it provides empirical diagnostics that help a learner
#' think about ideas such as diminishing adaptation and containment.
#'
#' @keywords internal
#' @useDynLib AdaptiveMCMCWorkflow, .registration = TRUE
#' @importFrom Rcpp evalCpp
"_PACKAGE"

#' Low-level Compiled Samplers
#'
#' These are the direct R wrappers generated by `Rcpp::compileAttributes()`.
#' Most users should call the higher-level R functions:
#' [basic_metropolis()], [adaptive_metropolis()],
#' [robust_adaptive_metropolis()], and [dram()].
#'
#' @name compiled_samplers
#' @aliases basic_metropolis_cpp adaptive_metropolis_cpp
#'   robust_adaptive_metropolis_cpp dram_cpp
#' @keywords internal
NULL

#' Run Basic Metropolis
#'
#' This is the fixed-kernel random-walk Metropolis baseline. The R wrapper
#' checks the inputs, calls `basic_metropolis_cpp()`, and then adds the common
#' package metadata used by the plotting and summary helpers.
#'
#' @param target_density Function of one numeric state vector `x` that returns
#'   the target density `pi(x)`.
#' @param log_target Deprecated compatibility alias. If supplied, the wrapper
#'   converts `log_target(x)` to `exp(log_target(x))`.
#' @param initial_state Numeric vector giving the starting value of the chain.
#' @param n_iter Number of Metropolis updates to run.
#' @param proposal_covariance Covariance matrix `S` in the Gaussian random-walk
#'   proposal `x^* = x + N(0, S)`.
#'
#' @return An object of class `"adaptive_mcmc_run"`.
#'
#' @examples
#' target <- make_correlated_gaussian_target()
#' run <- basic_metropolis(
#'   target_density = target$density,
#'   initial_state = target$recommended_initial,
#'   n_iter = 200,
#'   proposal_covariance = diag(2)
#' )
#' head(run$draws)
#'
#' @export
basic_metropolis <- function(target_density = NULL,
                             initial_state,
                             n_iter,
                             proposal_covariance = diag(length(initial_state)),
                             log_target = NULL) {
  # Validate the R inputs before calling the compiled sampler.
  target_density <- resolve_target_density(target_density, log_target)
  initial_state <- ensure_numeric_state(initial_state)
  n_iter <- ensure_positive_integer(n_iter, "n_iter")
  proposal_covariance <- ensure_square_matrix(
    proposal_covariance,
    length(initial_state),
    "proposal_covariance"
  )

  check_initial_density(target_density, initial_state)

  # Call the compiled implementation in src/basic_metropolis.cpp.
  result <- basic_metropolis_cpp(
    target_density = target_density,
    initial_state = initial_state,
    n_iter = n_iter,
    proposal_covariance = proposal_covariance
  )

  # Add the standard class and metadata expected by the R tools.
  standardise_sampler_output(result, initial_state = initial_state)
}

#' Run Adaptive Metropolis
#'
#' Adaptive Metropolis (AM) begins with a fixed pilot covariance and then learns
#' an empirical covariance from the realised chain. The R wrapper checks the
#' inputs, calls `adaptive_metropolis_cpp()`, and returns the result in the
#' standard package format.
#'
#' @param target_density Function of one numeric state vector `x` that returns
#'   the target density `pi(x)`.
#' @param log_target Deprecated compatibility alias. If supplied, the wrapper
#'   converts `log_target(x)` to `exp(log_target(x))`.
#' @param initial_state Numeric vector giving the starting value of the chain.
#' @param n_iter Number of Metropolis updates to run.
#' @param initial_proposal_covariance Initial covariance matrix `S_0` used
#'   before AM has enough history to adapt.
#' @param adapt_start Iteration at which AM is first allowed to replace `S_0`
#'   with the empirical covariance estimate built from past draws.
#' @param epsilon Small diagonal term in the AM update
#'   `S_n = (1 / n) sum_i (theta^(i) - theta_bar)(theta^(i) - theta_bar)^T + epsilon I`.
#' @param regularization Deprecated compatibility alias for `epsilon`.
#'
#' @return An object of class `"adaptive_mcmc_run"`.
#'
#' @examples
#' target <- make_correlated_t_target()
#' run <- adaptive_metropolis(
#'   target_density = target$density,
#'   initial_state = target$recommended_initial,
#'   n_iter = 300,
#'   initial_proposal_covariance = diag(2),
#'   adapt_start = 50
#' )
#' tail(run$adaptation_magnitude)
#'
#' @export
adaptive_metropolis <- function(target_density = NULL,
                                initial_state,
                                n_iter,
                                initial_proposal_covariance = diag(length(initial_state)),
                                adapt_start = 50L,
                                epsilon = 1e-8,
                                regularization = NULL,
                                log_target = NULL) {
  # Validate the R inputs before calling the compiled sampler.
  target_density <- resolve_target_density(target_density, log_target)
  initial_state <- ensure_numeric_state(initial_state)
  n_iter <- ensure_positive_integer(n_iter, "n_iter")
  initial_proposal_covariance <- ensure_square_matrix(
    initial_proposal_covariance,
    length(initial_state),
    "initial_proposal_covariance"
  )
  adapt_start <- ensure_positive_integer(adapt_start, "adapt_start")
  if (!is.null(regularization)) {
    epsilon <- regularization
  }

  epsilon <- ensure_positive_number(epsilon, "epsilon")

  if (adapt_start > n_iter) {
    stop("`adapt_start` must not be larger than `n_iter`.", call. = FALSE)
  }

  check_initial_density(target_density, initial_state)

  # Call the compiled implementation in src/adaptive_metropolis.cpp.
  result <- adaptive_metropolis_cpp(
    target_density = target_density,
    initial_state = initial_state,
    n_iter = n_iter,
    initial_proposal_covariance = initial_proposal_covariance,
    adapt_start = adapt_start,
    epsilon = epsilon
  )

  # Add the standard class and metadata expected by the R tools.
  standardise_sampler_output(result, initial_state = initial_state)
}

#' Run Robust Adaptive Metropolis
#'
#' Robust Adaptive Metropolis (RAM) adjusts its proposal using local acceptance
#' feedback rather than a full empirical covariance estimate. The R wrapper
#' checks the inputs, calls `robust_adaptive_metropolis_cpp()`, and returns the
#' result in the standard package format.
#'
#' @param target_density Function of one numeric state vector `x` that returns
#'   the target density `pi(x)`.
#' @param log_target Deprecated compatibility alias. If supplied, the wrapper
#'   converts `log_target(x)` to `exp(log_target(x))`.
#' @param initial_state Numeric vector giving the starting value of the chain.
#' @param n_iter Number of Metropolis updates to run.
#' @param initial_proposal_covariance Initial covariance matrix used to build
#'   the RAM proposal factor.
#' @param target_acceptance Target acceptance rate `alpha^*` that RAM tries to
#'   track over time.
#' @param adapt_exponent Exponent in the learning-rate schedule
#'   `eta_n = n^{-adapt_exponent}`. Larger values make the adaptation shrink
#'   faster.
#'
#' @return An object of class `"adaptive_mcmc_run"`.
#'
#' @examples
#' target <- make_high_dimensional_gaussian_target(dimension = 4)
#' run <- robust_adaptive_metropolis(
#'   target_density = target$density,
#'   initial_state = target$recommended_initial,
#'   n_iter = 300,
#'   initial_proposal_covariance = target$recommended_proposal_covariance
#' )
#' range(run$adaptation_magnitude)
#'
#' @export
robust_adaptive_metropolis <- function(target_density = NULL,
                                       initial_state,
                                       n_iter,
                                       initial_proposal_covariance = diag(length(initial_state)),
                                       target_acceptance = 0.234,
                                       adapt_exponent = 0.67,
                                       log_target = NULL) {
  # Validate the R inputs before calling the compiled sampler.
  target_density <- resolve_target_density(target_density, log_target)
  initial_state <- ensure_numeric_state(initial_state)
  n_iter <- ensure_positive_integer(n_iter, "n_iter")
  initial_proposal_covariance <- ensure_square_matrix(
    initial_proposal_covariance,
    length(initial_state),
    "initial_proposal_covariance"
  )
  target_acceptance <- ensure_probability(target_acceptance, "target_acceptance")
  adapt_exponent <- ensure_positive_number(adapt_exponent, "adapt_exponent")

  check_initial_density(target_density, initial_state)

  # Call the compiled implementation in src/robust_adaptive_metropolis.cpp.
  result <- robust_adaptive_metropolis_cpp(
    target_density = target_density,
    initial_state = initial_state,
    n_iter = n_iter,
    initial_proposal_covariance = initial_proposal_covariance,
    target_acceptance = target_acceptance,
    adapt_exponent = adapt_exponent
  )

  # Add the standard class and metadata expected by the R tools.
  standardise_sampler_output(result, initial_state = initial_state)
}

#' Run Delayed Rejection Adaptive Metropolis
#'
#' DRAM combines AM-style covariance learning with a smaller second-stage
#' proposal used after a first-stage rejection. The R wrapper checks the
#' inputs, calls `dram_cpp()`, and returns the result in the standard package
#' format.
#'
#' @param target_density Function of one numeric state vector `x` that returns
#'   the target density `pi(x)`.
#' @param log_target Deprecated compatibility alias. If supplied, the wrapper
#'   converts `log_target(x)` to `exp(log_target(x))`.
#' @param initial_state Numeric vector giving the starting value of the chain.
#' @param n_iter Number of Metropolis updates to run.
#' @param initial_proposal_covariance Initial covariance matrix for the
#'   first-stage proposal.
#' @param adapt_start Iteration at which AM-style covariance learning is first
#'   allowed to update the proposal.
#' @param delayed_rejection_scale Number `gamma` in `(0, 1]` that shrinks the
#'   first-stage covariance for the second-stage rescue proposal.
#' @param epsilon Small diagonal term in the AM-style update
#'   `S_n = (1 / n) sum_i (theta^(i) - theta_bar)(theta^(i) - theta_bar)^T + epsilon I`.
#' @param regularization Deprecated compatibility alias for `epsilon`.
#'
#' @return An object of class `"adaptive_mcmc_run"`.
#'
#' @examples
#' target <- make_dram_rescue_target()
#' run <- dram(
#'   target_density = target$density,
#'   initial_state = target$recommended_initial,
#'   n_iter = 300,
#'   initial_proposal_covariance = target$recommended_proposal_covariance,
#'   delayed_rejection_scale = target$recommended_delayed_rejection_scale
#' )
#' mean(run$second_stage_attempted)
#'
#' @export
dram <- function(target_density = NULL,
                 initial_state,
                 n_iter,
                 initial_proposal_covariance = diag(length(initial_state)),
                 adapt_start = 50L,
                 delayed_rejection_scale = 0.5,
                 epsilon = 1e-8,
                 regularization = NULL,
                 log_target = NULL) {
  # Validate the R inputs before calling the compiled sampler.
  target_density <- resolve_target_density(target_density, log_target)
  initial_state <- ensure_numeric_state(initial_state)
  n_iter <- ensure_positive_integer(n_iter, "n_iter")
  initial_proposal_covariance <- ensure_square_matrix(
    initial_proposal_covariance,
    length(initial_state),
    "initial_proposal_covariance"
  )
  adapt_start <- ensure_positive_integer(adapt_start, "adapt_start")
  delayed_rejection_scale <- ensure_positive_number(
    delayed_rejection_scale,
    "delayed_rejection_scale"
  )
  if (!is.null(regularization)) {
    epsilon <- regularization
  }

  epsilon <- ensure_positive_number(epsilon, "epsilon")

  if (adapt_start > n_iter) {
    stop("`adapt_start` must not be larger than `n_iter`.", call. = FALSE)
  }

  check_initial_density(target_density, initial_state)

  # Call the compiled implementation in src/dram.cpp.
  result <- dram_cpp(
    target_density = target_density,
    initial_state = initial_state,
    n_iter = n_iter,
    initial_proposal_covariance = initial_proposal_covariance,
    adapt_start = adapt_start,
    delayed_rejection_scale = delayed_rejection_scale,
    epsilon = epsilon
  )

  # Add the standard class and metadata expected by the R tools.
  standardise_sampler_output(result, initial_state = initial_state)
}

#' Run Standard Metropolis
#'
#' This is a presentation-friendly alias for [basic_metropolis()].
#'
#' @inheritParams basic_metropolis
#'
#' @return An object of class `"adaptive_mcmc_run"`.
#'
#' @export
run_metropolis <- function(target_density = NULL,
                           initial_state,
                           n_iter,
                           proposal_covariance = diag(length(initial_state)),
                           log_target = NULL) {
  basic_metropolis(
    target_density = target_density,
    initial_state = initial_state,
    n_iter = n_iter,
    proposal_covariance = proposal_covariance,
    log_target = log_target
  )
}

#' Run Adaptive Metropolis
#'
#' This is a presentation-friendly alias for [adaptive_metropolis()].
#'
#' @inheritParams adaptive_metropolis
#'
#' @return An object of class `"adaptive_mcmc_run"`.
#'
#' @export
run_adaptive_metropolis <- function(target_density = NULL,
                                    initial_state,
                                    n_iter,
                                    initial_proposal_covariance = diag(length(initial_state)),
                                    adapt_start = 50L,
                                    epsilon = 1e-8,
                                    regularization = NULL,
                                    log_target = NULL) {
  adaptive_metropolis(
    target_density = target_density,
    initial_state = initial_state,
    n_iter = n_iter,
    initial_proposal_covariance = initial_proposal_covariance,
    adapt_start = adapt_start,
    epsilon = epsilon,
    regularization = regularization,
    log_target = log_target
  )
}

#' Run Robust Adaptive Metropolis
#'
#' This is a presentation-friendly alias for
#' [robust_adaptive_metropolis()].
#'
#' @inheritParams robust_adaptive_metropolis
#'
#' @return An object of class `"adaptive_mcmc_run"`.
#'
#' @export
run_ram <- function(target_density = NULL,
                    initial_state,
                    n_iter,
                    initial_proposal_covariance = diag(length(initial_state)),
                    target_acceptance = 0.234,
                    adapt_exponent = 0.67,
                    log_target = NULL) {
  robust_adaptive_metropolis(
    target_density = target_density,
    initial_state = initial_state,
    n_iter = n_iter,
    initial_proposal_covariance = initial_proposal_covariance,
    target_acceptance = target_acceptance,
    adapt_exponent = adapt_exponent,
    log_target = log_target
  )
}

#' Run Delayed Rejection Adaptive Metropolis
#'
#' This is a presentation-friendly alias for [dram()].
#'
#' @inheritParams dram
#'
#' @return An object of class `"adaptive_mcmc_run"`.
#'
#' @export
run_dram <- function(target_density = NULL,
                     initial_state,
                     n_iter,
                     initial_proposal_covariance = diag(length(initial_state)),
                     adapt_start = 50L,
                     delayed_rejection_scale = 0.5,
                     epsilon = 1e-8,
                     regularization = NULL,
                     log_target = NULL) {
  dram(
    target_density = target_density,
    initial_state = initial_state,
    n_iter = n_iter,
    initial_proposal_covariance = initial_proposal_covariance,
    adapt_start = adapt_start,
    delayed_rejection_scale = delayed_rejection_scale,
    epsilon = epsilon,
    regularization = regularization,
    log_target = log_target
  )
}

#' Run the Full Teaching Suite
#'
#' This helper runs the four teaching samplers on the same target using one
#' consistent set of controls.
#'
#' @param target A target object created by one of the package target
#'   constructors.
#' @param n_iter Number of iterations used for each sampler.
#' @param initial_state Optional common starting point shared by all samplers.
#' @param controls Optional named list used to override sampler defaults. The
#'   top-level names should be `basic`, `adaptive`, `ram`, and `dram`.
#' @param seed Optional random seed set once before the suite run.
#'
#' @return An object of class `"adaptive_mcmc_comparison"`.
#'
#' @examples
#' comparison <- run_sampler_suite(make_correlated_t_target(), n_iter = 300, seed = 1)
#' names(comparison$runs)
#'
#' @export
run_sampler_suite <- function(target,
                              n_iter = 2000L,
                              initial_state = NULL,
                              controls = NULL,
                              seed = NULL) {
  target <- validate_target(target)
  n_iter <- ensure_positive_integer(n_iter, "n_iter")
  initial_state <- initial_state %||% target$recommended_initial %||% rep(0, target$dimension)
  initial_state <- ensure_numeric_state(initial_state)

  if (length(initial_state) != target$dimension) {
    stop("`initial_state` must match the target dimension.", call. = FALSE)
  }

  if (!is.null(seed)) {
    set.seed(as.integer(seed))
  }

  controls <- merge_sampler_controls(default_sampler_controls(target), controls)

  runs <- list(
    basic = basic_metropolis(
      target_density = target$density,
      initial_state = initial_state,
      n_iter = n_iter,
      proposal_covariance = controls$basic$proposal_covariance
    ),
    adaptive = adaptive_metropolis(
      target_density = target$density,
      initial_state = initial_state,
      n_iter = n_iter,
      initial_proposal_covariance = controls$adaptive$initial_proposal_covariance,
      adapt_start = controls$adaptive$adapt_start,
      epsilon = controls$adaptive$epsilon
    ),
    ram = robust_adaptive_metropolis(
      target_density = target$density,
      initial_state = initial_state,
      n_iter = n_iter,
      initial_proposal_covariance = controls$ram$initial_proposal_covariance,
      target_acceptance = controls$ram$target_acceptance,
      adapt_exponent = controls$ram$adapt_exponent
    ),
    dram = dram(
      target_density = target$density,
      initial_state = initial_state,
      n_iter = n_iter,
      initial_proposal_covariance = controls$dram$initial_proposal_covariance,
      adapt_start = controls$dram$adapt_start,
      delayed_rejection_scale = controls$dram$delayed_rejection_scale,
      epsilon = controls$dram$epsilon
    )
  )

  for (name in names(runs)) {
    runs[[name]]$target_name <- target$name
  }

  structure(
    list(
      target = target,
      initial_state = initial_state,
      n_iter = n_iter,
      controls = controls,
      runs = runs
    ),
    class = "adaptive_mcmc_comparison"
  )
}

#' Compare Adaptive Methods
#'
#' This high-level helper runs the four main samplers on one target, summarizes
#' them, and optionally times them.
#'
#' @param target A target object created by one of the package target
#'   constructors.
#' @param n_iter Number of iterations run for each sampler.
#' @param burn_in Number of initial iterations dropped before summaries are
#'   computed.
#' @param controls Optional named list of sampler-specific settings merged into
#'   the defaults.
#' @param seed Optional seed used before the comparison.
#' @param benchmark Logical. Should the function also time the samplers?
#' @param benchmark_repetitions Number of timing repetitions when
#'   `benchmark = TRUE`.
#'
#' @return A list with elements `comparison`, `summary`, and optionally
#'   `benchmark`. The object also has class `"adaptive_method_comparison"`.
#'
#' @examples
#' results <- compare_adaptive_methods(
#'   target = make_correlated_t_target(),
#'   n_iter = 250,
#'   burn_in = 50,
#'   seed = 1,
#'   benchmark = FALSE
#' )
#' results$summary
#'
#' @export
compare_adaptive_methods <- function(target,
                                     n_iter = 2000L,
                                     burn_in = 0L,
                                     controls = NULL,
                                     seed = NULL,
                                     benchmark = TRUE,
                                     benchmark_repetitions = 3L) {
  comparison <- run_sampler_suite(
    target = target,
    n_iter = n_iter,
    controls = controls,
    seed = seed
  )

  result <- list(
    comparison = comparison,
    summary = summarize_sampler_suite(comparison, burn_in = burn_in)
  )

  if (isTRUE(benchmark)) {
    result$benchmark <- benchmark_sampler_suite(
      target = target,
      n_iter = n_iter,
      repetitions = benchmark_repetitions,
      controls = controls,
      seed = seed
    )
  }

  class(result) <- c("adaptive_method_comparison", "list")
  result
}
