# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaptive_metropolis_cpp <- function(target_density, initial_state, n_iter, initial_proposal_covariance, adapt_start = 50L, epsilon = 1e-8) {
    .Call(`_AdaptiveMCMCWorkflow_adaptive_metropolis_cpp`, target_density, initial_state, n_iter, initial_proposal_covariance, adapt_start, epsilon)
}

basic_metropolis_cpp <- function(target_density, initial_state, n_iter, proposal_covariance) {
    .Call(`_AdaptiveMCMCWorkflow_basic_metropolis_cpp`, target_density, initial_state, n_iter, proposal_covariance)
}

dram_cpp <- function(target_density, initial_state, n_iter, initial_proposal_covariance, adapt_start = 50L, delayed_rejection_scale = 0.5, epsilon = 1e-8) {
    .Call(`_AdaptiveMCMCWorkflow_dram_cpp`, target_density, initial_state, n_iter, initial_proposal_covariance, adapt_start, delayed_rejection_scale, epsilon)
}

robust_adaptive_metropolis_cpp <- function(target_density, initial_state, n_iter, initial_proposal_covariance, target_acceptance = 0.234, adapt_exponent = 0.67) {
    .Call(`_AdaptiveMCMCWorkflow_robust_adaptive_metropolis_cpp`, target_density, initial_state, n_iter, initial_proposal_covariance, target_acceptance, adapt_exponent)
}
